# Site settings
title: The Brain Dump
header-img: img/home-bg.jpg
email: cayle@nimbustech.biz
description: "Cayle sharrock's coding blog. Mostly for my own reference, but you might find something useful here too."
baseurl: ""
url: "http://nimbustech.biz"
twitter_username: caylesharrock
github_username:  CjS77
website:  "http://nimbustech.biz"

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","srcimg"]

contacts:
  -  {icon: fa-twitter, text: 'caylesharrock', href: 'https://twitter.com/caylesharrock'}
  -  {icon: fa-github, text: 'CjS77', href: 'https://github.com/CjS77'}
  -  {icon: fa-envelope, text: 'cayle.sharrock@gmail.com', href: 'mailto:cayle.sharrock@gmail.com'}
  -  {icon: fa-linkedin, text: 'LinkedIn', href: 'http://za.linkedin.com/in/cjsharrock'}
  -  {icon: fa-stack-overflow, text: 'Stack Overflow', href: 'http://stackoverflow.com/users/1177536/cjs'}